services:
  lexigraph-website:
    container_name: lexigraph-website
    build:
      dockerfile: Dockerfile.Flask
    ports:
      - "7654:5000" # expose a custom port to Flask's port
    env_file:
      - .env
    volumes:
      - ./0_data:/data
    working_dir: /app
    networks:
      - lexigraph-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  ollama-container:
    build:
      dockerfile: Dockerfile.Ollama
    container_name: ollama-container
    ports:
      - "11434:11434" # Expose port 11434 to the host (not strictly necessary for internal communication)
    volumes:
      - ./2_ollama-data:/root/.ollama  # where llama3 model's data is stored
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=http://0.0.0.0
    networks:
      - lexigraph-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lexigraph-api-ollama:
    container_name: lexigraph-api-ollama
    build:
      dockerfile: Dockerfile.Api-Ollama
    ports:
      - "7653:7653" # allows testing from the localhost
    volumes:
      - ./0_audios:/app/audios
    working_dir: /app
    networks: 
      - lexigraph-network
    depends_on:
      - ollama-container
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  lexigraph-network:
    driver: bridge # every container is placed in this network
  
volumes:
  ollama-data: {}