FROM python:3.9-slim

WORKDIR /app

COPY requirements.Api-Ollama.txt ./
RUN pip install --no-cache-dir -r requirements.Api-Ollama.txt

COPY ./1_app-api/ /app/

EXPOSE 7653

# Better for real-time monitoring (specially for the DOcker containers)
ENV PYTHONUNBUFFERED=1 

CMD ["python3", "main.py"]
